### PR TITLE
Add tests for PR #38

### PR DESCRIPTION
**Pull request by UruDev**
In addition, fixes some minor stuff on core and removes very old unused code at the tests

### CODE REVIEW

**Comment by UruDev** [comment]
Seems like the test is failing in pyhton versions previous to 3.6, I'll check it. 
Let me know if you have some idea on why this is happening

**Comment by tcalmant** [comment]
Seems like it is a float precision error in the test:
```
FAIL: Tests support for custom writeObject (PR #38)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/tcalmant/python-javaobj/tests/tests_v2.py", line 565, in test_writeObject
    self.assertEqual(expected['custom_obj']['annotations'], super_data)
AssertionError: {'seed': 25214903879, 'haveNextNextGaussian': False, 'nextNextGaussian': 0.0} != {'nextNextGaussian': 1.245781777e-313, 'haveNextNextGaussian': False, 'seed': 0}
- {'haveNextNextGaussian': False, 'nextNextGaussian': 0.0, 'seed': 25214903879}
?                                                     ^ ^          ------ ----
+ {'haveNextNextGaussian': False, 'nextNextGaussian': 1.245781777e-313, 'seed': 0}
?                                                     ^ ^^^^^^^^^^^^^^
```

You could try to check the expected dictionary key by key and use [`self.assertAlmostEqual`](https://docs.python.org/3/library/unittest.html#unittest.TestCase.assertAlmostEqual)

**Comment by tcalmant** [comment]
Mmh I didn't see: there is also an error with the seed value

**Comment by tcalmant** [comment]
OK so the issue is in the test:
You use a dictionary, which were not ordered in Python < 3.6, so you don't read the fields in the expected order.
You should use 2 lists or a `collections.OrderedDict` object

**Comment by UruDev** [comment]
Ok, after some fails with dict ordering all tests are working and backward compatible

**Comment by tcalmant** [comment]
Great, I'll check that ASAP

**Comment by tcalmant** [comment]
Squashed, rebased and merged as commit b711479acdfc240910e4438a315e8c0746e7b71c

**Pull request closed without merging**
