### PR TITLE
Adds support for SC_WRITE_METHOD

### PR DESCRIPTION
**Pull request by UruDev**
Changes from this PR:
  * Check the flags and set the class type
  * Extends the API to add a custom read method to support WRCLASS
  * Adds previous object support as an array ClassDesc
  * _do_classdesc and _read_class_data refactors
  * Removes unused "must_be_new" parameter

### CODE REVIEW

**Comment by UruDev** [comment]
Test case:
* Java custom serialization:
`public class App implements Serializable {
	int val = 3;
	Obj custom_obj = new Obj(1, 4.5);
    public static void main( String[] args ) throws Exception
    {
       App programm = new App();
       programm.start();
    }

    public void start() throws Exception {
        FileOutputStream fileOut = new FileOutputStream("/tmp/serialized.ser");
        ObjectOutputStream out = new ObjectOutputStream(fileOut);
        this.writeObject(out);
        out.close();
        fileOut.close();
    }

    private void writeObject (ObjectOutputStream out) throws IOException {
        out.writeObject (this.custom_obj);
        out.writeInt (this.val);
    }
}

class Obj implements Serializable{
	int num;
	double doub;
	
	Obj(int num, double doub) {
		this.num = num;
		this.doub = doub;
	}
	private void writeObject (ObjectOutputStream out) throws IOException {
        ObjectOutputStream.PutField fields = out.putFields();
        fields.put("num", this.num);
        fields.put("doub", this.doub);
        out.writeFields();
    }
}`

Python custom transformer:
`class CustomTransformer:
    def __init__(self):
        self.name = "topics.Obj"
        self.fields = {
            'doub': javaobj.beans.FieldType.DOUBLE,
            'num': javaobj.beans.FieldType.INTEGER,
        }

    def create_instance(self, classdesc):
        if classdesc.name == self.name:
            # We can handle this class description
            return CustomTransformer()

        return None

    def load_custom_writeObject(self, parser, reader, name):
        if name == self.name:
            return self.get_class_description(parser)
        return None

    def get_class_description(self, parser):
        fields = []
        values = []
        for field_name, field_type in self.fields.items():
            values.append(parser._read_field_value(field_type))
            fields.append(javaobj.beans.JavaField(field_type, field_name))

        class_desc = javaobj.beans.JavaClassDesc(javaobj.beans.ClassDescType.NORMALCLASS)
        class_desc.name = self.name
        class_desc.desc_flags = javaobj.beans.ClassDataType.EXTERNAL_CONTENTS
        class_desc.fields = fields
        class_desc.field_data = values
        return class_desc`

**Comment by tcalmant** [comment]
Hi,
I've just updated your PR comment for a better format.
I'm reviewing the code, thanks for your contribution :)

**Comment by tcalmant** [comment]
3 tests are not working with this PR:
* Tests the handling of ArrayList, LinkedList and HashMap
* Reads a serialized object and checks its fields
* Tests support for Bool, Integer, Long classes (PR #27)

I'm investigating

**Comment by tcalmant** [comment]
OK so the issue is that the new transformer API wasn't backported to the DefaultObjectTransformer.
Could you update the `javaobj.v2.transformers` module accordingly, please ?

**Comment by UruDev** [comment]
All test fixed

**Comment by tcalmant** [comment]
OK, good for me

**Comment by tcalmant** [comment]
Last thing: which names do I have to add to the `AUTHORS` file ?

**Comment by UruDev** [comment]
Federico Alves

**Comment by tcalmant** [comment]
Hi again,
Could you provide a sample where the transformer is used ?
I can't find a situation where it's the case.
Also, what is `load_custom_writeObject` supposed to returned ?

**Comment by UruDev** [comment]
Hi! Yes sure, I'll make a new PR with a test implementation for a custom case.
As in the example of the first comment the load_custom_writeObject is intended to return a classDesc instance, I'll fix the class annotations too. Sorry about the missing of doc

**Pull request merged**
