### PR TITLE
Store the new object reference before processing it's members.

### PR DESCRIPTION
**Pull request by iciclespider**
As documented here http://download.oracle.com/javase/6/docs/platform/serialization/spec/protocol.html

    newObject:
        TC_OBJECT classDesc newHandle classdata[]  // data for each class

### CODE REVIEW

**Comment by tcalmant** [comment]
Thanks, this could remove some problems related to reference indices.
Although, it should be possible to update the stored reference at the end of the treatment, as it can be replaced by a new object by a transformer. (this is why tests currently fail)

**Comment by iciclespider** [comment]
The deserialization of some objects failed for me because the offsets got out of sync when the deserialization had to recurse and resolve the objects stores in the current object. While processing the sub-objects, an object got created and added to the references array. This sub-object was stored in the wrong offset, it should be after the top level object.

I did end up rearranging the transformers to instead be object creators which create the new java object from the classdec information. That way, it tracks the final object.

**Comment by tcalmant** [comment]
Did you push your latest changes ?
I'll test those changes against some of my code this week end.

Also, we should test if the "small hack" for [arrays](https://github.com/tcalmant/python-javaobj/blob/master/javaobj.py#L903-L907) is still required.

**Comment by iciclespider** [comment]
I pushed the version with the reworked transformers, and with that JavaArray hack removed, and now all tests pass. This does introduce a breaking change however in the way transformers are used. They really aren't transformers anymore, but creators.

**Comment by tcalmant** [comment]
All my tests passed and some more have been activated in tests.py.
I'll wait for @voetsjoeba to try the master version on ``pyjks`` before releasing a new version.

**Comment by voetsjoeba** [comment]
All good for pyjks:
```
$ (. ~/py2env/bin/activate; pip install git+https://github.com/tcalmant/python-javaobj.git --upgrade)
...
Successfully installed javaobj-py3-0.1.4
$ (. ~/py2env/bin/activate; python -m unittest discover 2>&1 | less)
...
Ran 27 tests in 0.039s
OK
```
```
$ (. ~/py3env/bin/activate; pip install git+https://github.com/tcalmant/python-javaobj.git --upgrade)
...
Successfully installed javaobj-py3-0.1.4
$ (. ~/py3env/bin/activate; python -m unittest discover 2>&1 | less)
...
Ran 27 tests in 0.048s
OK
```

**Comment by tcalmant** [comment]
Great !
The feature has been released as version 0.2.0, with a compatibility warning about object creator vs. transformer.

**Pull request merged**
