### PR TITLE
NumPy is imported only when needed

### PR DESCRIPTION
**Pull request by sarimak**
Fixes the issue #44.

### CODE REVIEW

**Comment by sarimak** [comment]
Is it worth of adding a test for the module-level side effect of the import? I don't think so but let me know if I should add it.

**Comment by tcalmant** [comment]
Hi,

I think it would be better to have a `try/except ImportError` instead of using `contextlib.suppress`, as the library is intended to keep some compatibility with Python 2.7.

Besides that, I'm OK with the contribution.
Using try/except also avoids the need for a new test as it would work like the original version (but delayed)

**Comment by sarimak** [comment]
Fixed to use the backward-compatible syntax (sorry for the force-push on my repo, I forgot to switch from work email to private).

**Comment by tcalmant** [comment]
No worries, thanks for your contribution

**Pull request merged**
